using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace TradeCompany1
{
    public partial class WebForm1 : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {

        }

        protected void Button1_Click(object sender, EventArgs e)
        {
            Panel1.Visible = true;
        }

        protected void Button7_Click(object sender, EventArgs e)
        {
            SqlDataSource1.Insert();
            GridView1.DataBind();
            nameCustomer.Text = "";
            surnameCustomer.Text = "";
            yearOfBirthCustomer.Text = "";
            Panel1.Visible = false;
        }

        protected void Button8_Click(object sender, EventArgs e)
        {
            nameCustomer.Text = "";
            surnameCustomer.Text = "";
            yearOfBirthCustomer.Text = "";
            Panel1.Visible = false;
        }

        protected void Button4_Click(object sender, EventArgs e)
        {
            Panel2.Visible = true;
        }

        protected void Button9_Click(object sender, EventArgs e)
        {
            SqlDataSource2.Insert();
            GridView2.DataBind();
            titleOrder.Text = "";
            priceOrder.Text = "";
            quantOrder.Text = "";
            Panel2.Visible = false;
        }

        protected void Button10_Click(object sender, EventArgs e)
        {
            titleOrder.Text = "";
            priceOrder.Text = "";
            quantOrder.Text = "";
            Panel2.Visible = false;
        }

        protected void GridView1_SelectedIndexChanged(object sender, EventArgs e)
        {
            Button4.Visible = true;
            Button5.Visible = true;
            Button6.Visible = true;
        }

        protected void Button2_Click(object sender, EventArgs e)
        {
            if (Button2.Text == "Обновить данные")
            {
                GridView1.AutoGenerateEditButton = true;

                Button2.Text = "Закончить редактирование";
            }
            else
            {

                GridView1.AutoGenerateEditButton = false;
                Button2.Text = "Обновить заказы";

            }
        }

        protected void Button5_Click(object sender, EventArgs e)
        {
            if (Button5.Text == "Обновить")
            {
                GridView2.AutoGenerateEditButton = true;

                Button5.Text = "Закончить редактирование";
            }
            else
            {

                GridView2.AutoGenerateEditButton = false;
                Button5.Text = "Обновить";

            }
        }

        protected void Button6_Click(object sender, EventArgs e)
        {
            if (Button6.Text == "Удалить")
            {
                GridView2.AutoGenerateDeleteButton = true;

                Button6.Text = "Закончить удаление";
            }
            else
            {

                GridView2.AutoGenerateDeleteButton = false;
                Button6.Text = "Удалить";

            }
        }

        protected void Button3_Click(object sender, EventArgs e)
        {
            if (Button3.Text == "Удалить заказчика")
            {
                GridView1.AutoGenerateDeleteButton = true;

                Button3.Text = "Закончить удаление";
            }
            else
            {

                GridView1.AutoGenerateDeleteButton = false;
                Button3.Text = "Удалить заказчика";

            }
        }
    }
}